services:
  HeimrichHannot\LoginRegistrationBundle\:
    resource: '../src/{Controller,EventListener,Registration,Security}/*'
    autoconfigure: true
    autowire: true

  HeimrichHannot\LoginRegistrationBundle\Security\User\ContaoUserProviderDecorator:
    decorates: 'contao.security.frontend_user_provider'
    autowire: true
    bind:
      $contaoUserProvider: '@.inner'